apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-workshop
  labels:
    app: aks-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-workshop
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: aks-workshop
    spec:
      containers:
      - name: aks-workshop
        image: gammondev.azurecr.io/gammonmike/aks_workshop:$BUILD_ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aks-workshop
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: aks-workshop									
